### ISSUE TITLE
Use Meson as build system

### ISSUE THREAD

**Issue by Luni-4** [rr-/CRC-manipulator#12]
It would be more comfortable compile and cross-compile `CRC-manipulator` using `Meson` as build system.

**Comment by rr-** [comment]
This requires a heavily tested PR from someone else.

**Comment by Luni-4** [comment]
I can work on this. I'm very busy lately, so it will take some time :)

**Comment by strangekillers** [comment]
Couldn't open file for writing
why
???

**Comment by Luni-4** [comment]
> Couldn't open file for writing
> why
> ??? 

@strangekillers 

Do you want the PR associated to this issue to get merged or the problem is somewhere else?

**Comment by Luni-4** [comment]
Closes since #13 is landed
